# -*- coding: utf-8 -*-
"""internshiptask3HousingFinalversion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1De7RXZrY0bH4I2VQUpD08oOGtCX6cm-n
"""

import os
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms, models
from PIL import Image
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error
import matplotlib.pyplot as plt
from google.colab import drive

# Mount Google Drive
drive.mount('/content/drive')

# Load CSV
csv_path = "/content/drive/MyDrive/Colab Notebooks/task/socal2.csv"
image_folder = "/content/drive/MyDrive/Colab Notebooks/task/"
df = pd.read_csv(csv_path)

# Clean column names
df.columns = df.columns.str.strip()
df = df.rename(columns={'bed': 'bedrooms', 'bath': 'bathrooms', 'sqft': 'sqft', 'n_citi': 'city_code'})

# Keep only numeric columns we need
df['bedrooms'] = pd.to_numeric(df['bedrooms'], errors='coerce')
df['bathrooms'] = pd.to_numeric(df['bathrooms'].astype(str).str.extract('(\d+\.?\d*)')[0], errors='coerce')
df['sqft'] = pd.to_numeric(df['sqft'], errors='coerce')
df['city_code'] = pd.to_numeric(df['city_code'], errors='coerce')
df['price'] = pd.to_numeric(df['price'], errors='coerce')

# Remove rows with missing price
df = df.dropna(subset=['price'])

# Fill missing values with median
for col in ['bedrooms', 'bathrooms', 'sqft', 'city_code']:
    df[col] = df[col].fillna(df[col].median())

print(f"Total houses in CSV: {len(df)}")

#image_folder = "/content/drive/MyDrive/"

def find_image(img_id, folder):
    """Find image file for a given ID"""
    if pd.isna(img_id):
        return None
    for ext in ['.jpg', '.jpeg', '.png']:
        path = os.path.join(folder, f"{int(img_id)}{ext}")
        if os.path.exists(path):
            return path
    return None

# Add image paths to dataframe
df['image_path'] = df['image_id'].apply(lambda x: find_image(x, image_folder))
has_images = df['image_path'].notna().any()

if has_images:
    # Keep only rows with images
    df = df[df['image_path'].notna()].reset_index(drop=True)
    print(f"Houses with images: {len(df)}")
else:
    print("No images found - using tabular data only")

# 3. PREPARE FEATURES AND TARGET (ALL FROM SAME DATAFRAME)

# Select features
features = ['bedrooms', 'bathrooms', 'sqft', 'city_code']
X = df[features].values.astype(np.float32)
y = df['price'].values.astype(np.float32)

# Scale features
scaler = StandardScaler()
X = scaler.fit_transform(X)

print(f"Features shape: {X.shape}")
print(f"Target shape: {y.shape}")
print(f"Price range: ${y.min():,.0f} - ${y.max():,.0f}")

# 4. CREATE TRAIN/VAL/TEST SPLITS


# First split: 80% train+val, 20% test
X_temp, X_test, y_temp, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Second split: split train+val into 80% train, 20% val (which is 64% and 16% of original)
X_train, X_val, y_train, y_val = train_test_split(X_temp, y_temp, test_size=0.25, random_state=42)

print(f"\nData splits:")
print(f"  Training: {len(X_train)} samples")
print(f"  Validation: {len(X_val)} samples")
print(f"  Test: {len(X_test)} samples")

# Split image paths to match the data splits
if has_images:
    # Get image paths for each split using the same indices
    paths = df['image_path'].values

    # Use indices to ensure proper alignment
    indices = np.arange(len(df))
    temp_idx, test_idx, _, _ = train_test_split(indices, y, test_size=0.2, random_state=42)
    train_idx, val_idx, _, _ = train_test_split(temp_idx, y_temp, test_size=0.25, random_state=42)

    paths_train = paths[train_idx]
    paths_val = paths[val_idx]
    paths_test = paths[test_idx]
else:
    paths_train = paths_val = paths_test = None
# ============================================
# 5. CREATE PYTORCH DATASET
# ============================================

class HouseDataset(Dataset):
    def __init__(self, X, y, image_paths=None, transform=None):
        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.float32)
        self.image_paths = image_paths
        self.transform = transform

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        # Get tabular data
        tabular = self.X[idx]

        # Get image (or blank if no image)
        #if self.image_paths is not None and self.image_paths[idx]:
        if self.image_paths is not None and self.image_paths[idx] is not None:
            try:
                img = Image.open(self.image_paths[idx]).convert('RGB')
                if self.transform:
                    img = self.transform(img)
            except:
                img = torch.zeros(3, 224, 224)
        else:
            img = torch.zeros(3, 224, 224)

        return tabular, img, self.y[idx]

# Image preprocessing
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
])

# Create datasets
train_dataset = HouseDataset(X_train, y_train, paths_train, transform)
val_dataset = HouseDataset(X_val, y_val, paths_val, transform)
test_dataset = HouseDataset(X_test, y_test, paths_test, transform)

# Create data loaders
batch_size = 4 if has_images and len(X_train) >= 4 else 1
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

print(f"\nData loaders created with batch size: {batch_size}")

# ============================================
# 6. BUILD MODEL
# ============================================

class PricePredictor(nn.Module):
    def __init__(self, use_images=True):
        super(PricePredictor, self).__init__()

        self.use_images = use_images

        # Image branch (CNN)
        if use_images:
            cnn = models.resnet18(pretrained=True)
            self.cnn = nn.Sequential(*list(cnn.children())[:-1])  # Remove last layer
            # Freeze early layers
            for param in list(self.cnn.parameters())[:-4]:
                param.requires_grad = False

            # Tabular branch
            self.tabular_net = nn.Sequential(
                nn.Linear(4, 32), nn.ReLU(), nn.Dropout(0.2),
                nn.Linear(32, 16), nn.ReLU()
            )
            combined_size = 512 + 16
        else:
            combined_size = 4

        # Combined network
        self.predictor = nn.Sequential(
            nn.Linear(combined_size, 128), nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(128, 64), nn.ReLU(), nn.Dropout(0.2),
            nn.Linear(64, 32), nn.ReLU(),
            nn.Linear(32, 1)
        )

    def forward(self, tabular, image):
        if self.use_images:
            # Get image features
            img_features = self.cnn(image)
            img_features = img_features.view(img_features.size(0), -1)

            # Get tabular features
            tab_features = self.tabular_net(tabular)

            # Combine
            combined = torch.cat([img_features, tab_features], dim=1)
        else:
            combined = tabular

        # Predict price
        return self.predictor(combined).squeeze()

# ============================================
# 7. TRAIN MODEL
# ============================================

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = PricePredictor(use_images=has_images).to(device)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)

print(f"\n{'='*50}")
print(f"Training Configuration")
print(f"{'='*50}")
print(f"Device: {device}")
print(f"Using images: {has_images}")
print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")

# Training loop
print(f"\nTraining started...")
print(f"{'='*50}")

for epoch in range(30):
    # Training phase
    model.train()
    train_loss = 0
    for tabular, img, price in train_loader:
        tabular, img, price = tabular.to(device), img.to(device), price.to(device)

        optimizer.zero_grad()
        pred = model(tabular, img)
        loss = criterion(pred, price)
        loss.backward()
        optimizer.step()

        train_loss += loss.item()

    # Validation phase
    model.eval()
    val_loss = 0
    with torch.no_grad():
        for tabular, img, price in val_loader:
            tabular, img, price = tabular.to(device), img.to(device), price.to(device)
            pred = model(tabular, img)
            val_loss += criterion(pred, price).item()

    # Print progress every 5 epochs
    if (epoch + 1) % 5 == 0:
        avg_train_loss = train_loss / len(train_loader)
        avg_val_loss = val_loss / len(val_loader)
        print(f"Epoch {epoch+1:2d}/30 - Train Loss: {avg_train_loss:.4f}, Val Loss: {avg_val_loss:.4f}")

print("Training complete!")

# ============================================
# 8. EVALUATE MODEL
# ============================================

print(f"\n{'='*50}")
print("TEST SET RESULTS")
print(f"{'='*50}")

model.eval()
predictions, actuals = [], []
with torch.no_grad():
    for tabular, img, price in test_loader:
        tabular, img = tabular.to(device), img.to(device)
        pred = model(tabular, img)
        predictions.extend(pred.cpu().numpy())
        actuals.extend(price.numpy())

# Convert to numpy arrays
# Handle both scalar and batch predictions
if pred.dim() == 0:  # Scalar (batch_size=1)
    predictions.append(pred.item())
    actuals.append(price.item())
else:  # Batch
    predictions.extend(pred.cpu().numpy().tolist())
    actuals.extend(price.cpu().numpy().tolist())
# Calculate metrics
mae = mean_absolute_error(actuals, predictions)
rmse = np.sqrt(mean_squared_error(actuals, predictions))

# Calculate R²
ss_res = np.sum((actuals - predictions) ** 2)
ss_tot = np.sum((actuals - np.mean(actuals)) ** 2)
r2 = 1 - (ss_res / ss_tot)

print(f"Mean Absolute Error (MAE):  ${mae:,.2f}")
print(f"Root Mean Square Error (RMSE): ${rmse:,.2f}")
print(f"R² Score: {r2:.4f}")
print(f"\nAverage House Price: ${np.mean(actuals):,.2f}")
print(f"MAE as % of average: {(mae/np.mean(actuals))*100:.1f}%")

# ============================================
# 9. VISUALIZE RESULTS
# ============================================

fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Scatter plot: Actual vs Predicted
ax1.scatter(actuals, predictions, alpha=0.6, edgecolors='black', linewidth=0.5)
ax1.plot([actuals.min(), actuals.max()], [actuals.min(), actuals.max()], 'r--', lw=2, label='Perfect Prediction')
ax1.set_xlabel('Actual Price ($)', fontsize=12)
ax1.set_ylabel('Predicted Price ($)', fontsize=12)
ax1.set_title(f'Actual vs Predicted Prices\nMAE: ${mae:,.0f}, R²: {r2:.3f}', fontsize=12)
ax1.legend()
ax1.grid(True, alpha=0.3)

# Residual plot
residuals = actuals - predictions
ax2.scatter(predictions, residuals, alpha=0.6, edgecolors='black', linewidth=0.5)
ax2.axhline(y=0, color='r', linestyle='--', lw=2)
ax2.set_xlabel('Predicted Price ($)', fontsize=12)
ax2.set_ylabel('Residuals ($)', fontsize=12)
ax2.set_title(f'Prediction Errors\nMean Residual: ${np.mean(residuals):.0f}', fontsize=12)
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Distribution of errors
plt.figure(figsize=(10, 5))
plt.hist(residuals, bins=20, edgecolor='black', alpha=0.7)
plt.xlabel('Prediction Error ($)', fontsize=12)
plt.ylabel('Frequency', fontsize=12)
plt.title(f'Distribution of Prediction Errors\nStd Dev: ${np.std(residuals):,.0f}', fontsize=12)
plt.axvline(x=0, color='r', linestyle='--', linewidth=2)
plt.grid(True, alpha=0.3)
plt.show()

# ============================================
# 10. FEATURE IMPORTANCE (Random Forest)
# ============================================

print(f"\n{'='*50}")
print("TABULAR FEATURE IMPORTANCE")
print(f"{'='*50}")

from sklearn.ensemble import RandomForestRegressor

# Train a simple model to get feature importance
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

importance = pd.DataFrame({
    'Feature': features,
    'Importance': rf.feature_importances_
}).sort_values('Importance', ascending=False)

for _, row in importance.iterrows():
    print(f"  {row['Feature']}: {row['Importance']:.3f}")

# Plot feature importance
plt.figure(figsize=(8, 5))
plt.barh(importance['Feature'], importance['Importance'])
plt.xlabel('Importance', fontsize=12)
plt.title('Feature Importance for Price Prediction', fontsize=12)
plt.gca().invert_yaxis()
plt.tight_layout()
plt.show()

print(f"\n{'='*50}")
print("✅ Model training and evaluation complete!")
print(f"{'='*50}")