# -*- coding: utf-8 -*-
"""task4BotStreamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQiQbosVDwKf_du_ZvKf-8LTgpVlRfwu
"""

!pip install streamlit sentence-transformers faiss-cpu numpy pyngrok

from pyngrok import ngrok

ngrok.set_auth_token("33va9OTVwfC3gqkY1iuQmbb1w28_7bCQRqBUJM2bbKv69XypX")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import numpy as np
# from sentence_transformers import SentenceTransformer
# import faiss
# 
# knowledge_chunks = [
#     "AI is artificial intelligence that simulates human thinking.",
#     "Machine learning enables computers to learn from data.",
#     "RAG combines retrieval with generation.",
#     "Vector databases store embeddings for similarity search.",
#     "Chatbots use context to answer better."
# ]
# 
# @st.cache_resource
# def load_model():
#     return SentenceTransformer('all-MiniLM-L6-v2')
# 
# model = load_model()
# 
# embeddings = model.encode(knowledge_chunks, normalize_embeddings=True)
# embeddings = np.array(embeddings).astype('float32')
# 
# index = faiss.IndexFlatIP(embeddings.shape[1])
# index.add(embeddings)
# 
# def get_answer(q):
#     q_emb = model.encode([q], normalize_embeddings=True)
#     q_emb = np.array(q_emb).astype('float32')
#     _, idx = index.search(q_emb, k=2)
#     return "\n".join([knowledge_chunks[i] for i in idx[0]])
# 
# st.title("🧠 RAG Chatbot")
# 
# if "chat" not in st.session_state:
#     st.session_state.chat = []
# 
# msg = st.chat_input("Ask something...")
# 
# if msg:
#     ans = get_answer(msg)
#     st.session_state.chat.append(("You", msg))
#     st.session_state.chat.append(("Bot", ans))
# 
# for r, m in st.session_state.chat:
#     st.write(f"**{r}:** {m}")

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &

from pyngrok import ngrok

public_url = ngrok.connect(8501)
print("Open this link:", public_url)