# -*- coding: utf-8 -*-
"""task4chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z3OHEeh3THoEPwIVEKreTBjknF0eNmur
"""

!pip install gradio sentence-transformers faiss-cpu numpy

import gradio as gr
import numpy as np
from sentence_transformers import SentenceTransformer
import faiss

# -----------------------
# Knowledge Base
# -----------------------
knowledge_chunks = [
    "AI is artificial intelligence that simulates human thinking.",
    "Machine learning enables computers to learn from data without explicit programming.",
    "RAG (Retrieval-Augmented Generation) combines search with language generation.",
    "Vector databases store embeddings for similarity search.",
    "Chatbots with memory can remember previous conversations and provide context-aware responses."
]

# -----------------------
# Model
# -----------------------
model = SentenceTransformer('all-MiniLM-L6-v2')

# Normalize embeddings (important)
embeddings = model.encode(knowledge_chunks, normalize_embeddings=True)
embeddings = np.array(embeddings).astype('float32')

# -----------------------
# FAISS Index (Cosine similarity)
# -----------------------
index = faiss.IndexFlatIP(embeddings.shape[1])
index.add(embeddings)

# -----------------------
# Chat Function
# -----------------------
def chat(message, history):

    # Simple greeting handling
    greetings = ["hi", "hello", "hey", "hey there"]
    if message.lower().strip() in greetings:
        return "Hello! How can I help you today?"

    # Encode query
    query_embedding = model.encode([message], normalize_embeddings=True)
    query_embedding = np.array(query_embedding).astype('float32')

    # Retrieve top match
    distances, indices = index.search(query_embedding, k=2)

    # Build context
    context = "\n".join([knowledge_chunks[i] for i in indices[0]])

    # Clean response (NO repeating question)
    response = f"""Answer:

{context}
"""

    return response

# -----------------------
# Gradio UI
# -----------------------
gr.ChatInterface(
    fn=chat,
    title="Simple RAG Chatbot",
    description="Pure Python RAG (FAISS + SentenceTransformers)"
).launch(share=True)